### PR TITLE
Use i18n in active_admin.rb

### LINKED ISSUE #3: Use i18n in active_admin.rb
Let's use Rails' I18n feature when initializing `active_admin` [here](https://github.com/Codeminer42/Punchclock/blob/master/config/initializers/active_admin.rb#L25).

### PR DESCRIPTION
**Pull request by joaoguiIherme**
Added the translation string in the i18n resources and replaced the hardcoded label with a call to the rails I18N service.

Closes #3

### CODE REVIEW

**Comment by joaoguiIherme** [comment]
Closes #3

**Review by wenderjean — COMMENTED** [review]
Adiciona no arquivo `pt-BR/active_admin.yml` também por favor.

**Comment by joaoguiIherme** [comment]
If you're talking about the same structure, it already exists [HERE](https://github.com/Codeminer42/Punchclock/blob/f1bf3b30ec9106776736a12c4054e3b234804233/config/locales/pt-BR/active_admin.yml#L25-L28)

**Comment by wenderjean** [comment]
It seems we have a similar translation [here](https://github.com/Codeminer42/Punchclock/blob/9d3adfcef006b9b975e8e4577894a07f0a7d81ca/config/locales/pt-BR/pt-BR.yml#L24), after a quick research I couldn't find someplace using it, would you mind to take a look and remove it in this PR?

**Comment by joaoguiIherme** [comment]
Sure!

**Review by adbatista — APPROVED** [review]

**Pull request merged**
