### PR TITLE
Oauth token moved from query to header#23

### PR DESCRIPTION
**Pull request by carlosdanielpohlod**
Added header:Authorization:"token {my_Oauth_token}" in lib/tasks/github. 

ps: this issue also was reported in the github_api gem: https://github.com/piotrmurach/github/issues/374

### CODE REVIEW

**Comment by adbatista** [comment]
please rebase your branch aginst master

**Comment by carlosdanielpohlod** [comment]
> please rebase your branch aginst master

done

**Comment by wenderjean** [comment]
Closes: https://github.com/Codeminer42/Punchclock/issues/23

**Comment by wenderjean** [comment]
It seems you still have issues with rebase, those changes related to the Ruby version shouldn't be present here.

**Pull request closed without merging**
