### PR TITLE
add dev-caching tmp file

### PR DESCRIPTION
**Pull request by andreLumor**
Since /tmp files are ignored, def-caching file had to be force added.
Now development environment is caching correctly.

### CODE REVIEW

**Comment by adbatista** [comment]
why do we need this?

**Comment by andreLumor** [comment]
> why do we need this?

Rails uses this file as cache in development environment.
Without it we are unable to deny JWT tokens (jti denylist is cached).

**Comment by adbatista** [comment]
but i still don't get why this need to be added on git, if the file is being created when running, should be fine

**Comment by andreLumor** [comment]
The file is not created when running. If it doesn't exist, rails simply won't do caching on development env.

**Comment by adbatista** [comment]
I got it, but if this is always enabled we may have some issues in some other parts of the app, is better to enable it only if needed
running `rails dev:cache`

**Pull request closed without merging**
